"""Initial migration

Revision ID: adede84b91cd
Revises: 
Create Date: 2025-02-27 14:00:26.285343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adede84b91cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joinID', sa.String(length=50), nullable=False))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('joinID')

    # ### end Alembic commands ###
